# Usar una imagen de Node.js como base
FROM node:14.18.1-alpine

# Establecer el directorio de trabajo en /app
WORKDIR /app

# Instalar dependencias del sistema necesarias
RUN apk add --no-cache bash

# Copiar el package.json y el yarn.lock (si existe)
COPY package.json yarn.lock ./

# Instalar las dependencias de la aplicación
RUN yarn install --frozen-lockfile

# Copiar todo el código fuente de la aplicación
COPY . .

# Exponer el puerto en el que la aplicación se ejecutará
EXPOSE 3000

# Comando para ejecutar la aplicación en modo desarrollo
CMD ["yarn", "run", "start"]