export enum TitleButtons {
    DELETE = 'Eliminar',
    SAVE = 'Guardar',
    NEXT = 'Siguiente',
    BACK = 'Atrás',
    PUBLISH = 'Publicar',
    ACCEPT = 'Aceptar',
    SEND = 'Enviar',
    CONTINUE = 'Continuar',
    ADD = 'Agregar',
    CREATE = 'Crear',
    ADD_OTHER = 'Agregar otra',
    CANCEL = 'Cancelar',
    CANCEL_RENEWAL = 'Cancelar renovación',
    SAVE_SEND = 'Guardar y enviar',
    DISCARD_CHANGE = 'Descartar cambios ',
    SAVE_DRAFT = 'Guardar como borrador',
    LOGIN = 'Iniciar sesión',
    PREV_STEP = 'Regresar al paso anterior',
    NEXT_STEP = 'Ir al paso siguiente',
    CLOSE = 'Cerrar',
    RENEW = 'Renovar',
    SEARCH = 'Buscar',
}
