import { IGenericRecord } from '@models/GenericRecord';
export const INPUTS_STATE = (): IGenericRecord => {
    return {
        associated_document_prefix: '',
        associated_document_number: '',
        date_issue_associated_document: '',
        hour_issue_associated_document: '',
        prefix: '',
        invoice_number: '',
        badge: '',
        date_issue: ''  ,
        broadcast_time: '',
        due_date: '',
        reason_rejection: '',
        purchase_order_number: '',
        customer_document_type: '',
        customer_name: '',
        address: '',
        department_state: '',
        postal_code: '',
        purchase_manager: '',
        purchase_number_document_number: '',
        collection_days: '',
        way_pay: '',
        fiscal_responsibility: '',
        observations: '',
        sales_manager: '',
        customer_document_number: '',
        email: '',
        country: '',
        city: '',
        phone: '',
        type_document_purchase_manager: '',
        payment_type: '',
        type_taxpayer: '',
        tax_detail: '',
        seller_type_document: '',
        seller_document_number: '',
    };
};