export enum INVOICE_TYPE {
    PURCHASE_SUPPLIER = 'PURCHASE_SUPPLIER',
    INVOICE = 'INVOICE',
    DEBIT_NOTE = 'DEBIT_NOTE',
    QUOTE = 'QUOTE',
    SUPPORTING_DOCUMENT = 'SUPPORTING_DOCUMENT',
    UNASSIGNED = 'UNASSIGNED',
}

export const CUSTOMER_TYPE = [INVOICE_TYPE.INVOICE, INVOICE_TYPE.DEBIT_NOTE];
export const SUPPLIER_TYPE = [INVOICE_TYPE.PURCHASE_SUPPLIER];
