import { Dispatch, SetStateAction } from 'react';
import { v4 as uuid } from 'uuid';
import { SelectedOption } from 'react-select-search';
import { IOptionSelect } from '@components/input';
import { IBodyTable, IHeaderTable } from '@components/table';
import { ITableFieldType } from '@constants/TableFieldType';
import { IGenericRecord } from '@models/GenericRecord';

export { ContentTable } from './content-table/ContentTable';
export { ModalCustomHour } from './modal-custom/ModalCustom';
export { TimeFields } from './time-fields/timeFields';

/**
 * Structure table company locations
 *
 * @returns IHeaderTable[]
 *  */
export const headersTableLocations: IHeaderTable[] = [
    {
        className: 'w-8',
        wrapperClassName: 'w-8',
    },
    {
        title: '*Nombre sede',
        wrapperClassName: 'w-53',
    },
    {
        title: 'Dirección',
        wrapperClassName: 'w-85.5',
    },
    {
        title: 'Color en calendario',
        wrapperClassName: 'w-37',
    },
];

/** This enum has four
members: `VIRTUAL`, `ON_SITE`, `VIRTUAL_ID`, and `ON_SITE_ID`. Each member is assigned a string
value.

    @enum {string}
*/
export enum typesAppointmentTable {
    VIRTUAL = 'Virtual',
    ON_SITE = 'Presencial',
    VIRTUAL_ID = 'VIRTUAL',
    ON_SITE_ID = 'ON_SITE',
}

/**
 * This contain the types of the day to used in a timeSlot. 
    
    @enum {string}
*/
export enum timeSlotType {
    MORNING = 'morning',
    AFTERNOON = 'afternoon',
}

/* Each object represents an option for selecting a duration. Each object has properties such as key, value,
id, and code, which are used to identify and display the duration option. */
export const duration: IOptionSelect[] = [
    {
        key: uuid(),
        value: '30 minutos',
        id: uuid(),
        code: '30',
    },
    {
        key: uuid(),
        value: '1 hora',
        id: uuid(),
        code: '60',
    },
    {
        key: uuid(),
        value: '2 horas',
        id: uuid(),
        code: '120',
    },
];

/* Each object represents a color
option and has properties such as `key`, `value`, `id`, and `code`. The `key` and `id` properties
are generated using the `uuid()` function, which generates a unique identifier. The `value` property
represents the name of the color, and the `code` property represents the hexadecimal code for the
color. */
const colors: IOptionSelect[] = [
    {
        key: uuid(),
        value: 'Azul',
        id: uuid(),
        code: '#0B2C4C',
    },
    {
        key: uuid(),
        value: 'Celeste',
        id: uuid(),
        code: '#00A99D',
    },
    {
        key: uuid(),
        value: 'lila',
        id: uuid(),
        code: '#81319B',
    },
    {
        key: uuid(),
        value: 'Rojo',
        id: uuid(),
        code: '#F6846B',
    },
    {
        key: uuid(),
        value: 'Gris',
        id: uuid(),
        code: '#AEAEAF',
    },
    {
        key: uuid(),
        value: 'Amarillo',
        id: uuid(),
        code: '#E1C28F',
    },
    {
        key: uuid(),
        value: 'Rosado',
        id: uuid(),
        code: '#933477',
    },
    {
        key: uuid(),
        value: 'Purpura',
        id: uuid(),
        code: '#4D387E',
    },
    {
        key: uuid(),
        value: 'Verde',
        id: uuid(),
        code: '#006400',
    },
];

/**  
 * Each object has properties such as
`key`, `value`, `id`, and `code`. The `key` property is assigned a unique identifier generated by
the `uuid()` function. The `value` property represents the display value of the option (e.g.,
'Presencial' or 'Virtual'). The `id` property represents the type of appointment (e.g.,
`typesAppointmentTable.ON_SITE` or `typesAppointmentTable.VIRTUAL`). The 
    @returns IOptionSelect[]
*/
export const optionTypeAppointment = [
    {
        key: uuid(),
        value: 'Presencial',
        id: typesAppointmentTable.ON_SITE_ID,
        code: '#4D387E',
    },
    {
        key: uuid(),
        value: 'Virtual',
        id: typesAppointmentTable.VIRTUAL_ID,
        code: '#006400',
    },
];

/**
 * Structure table company Appointment
 *
 * @returns IHeaderTable[]
 *  */
export const headersTableAppointment = (typesAppointment: IGenericRecord): IHeaderTable[] => {
    const { virtual, inPerson } = typesAppointment;
    return virtual && !inPerson
        ? [
              {
                  className: 'w-8',
                  wrapperClassName: 'w-8',
              },
              {
                  title: '*Nombre de la cita',
                  wrapperClassName: 'w-53',
              },
              {
                  title: 'Duración',
                  wrapperClassName: 'w-32',
              },
          ]
        : [
              {
                  className: 'w-8',
                  wrapperClassName: 'w-8',
              },
              {
                  title: '*Nombre de la cita',
                  wrapperClassName: 'w-53',
              },
              ((!virtual && !inPerson) || (virtual && inPerson)) && {
                  title: '*Tipo de cita',
                  wrapperClassName: 'w-40.80',
              },
              {
                  title: '*Sede',
                  wrapperClassName: 'w-48',
              },
              {
                  title: 'Duración',
                  wrapperClassName: 'w-32',
              },
          ];
};

/**
 * Function that returns the entries contained in the Locations table
 * 
 * @param handleChange?: (
        e: React.ChangeEvent<HTMLInputElement> - event,
        item: IGenericRecord - item being modified,
        name: string | undefined - name input
    )  - event that is executed when doing a handlechange
 * @returns IBodyTable[]
 */
export const fieldsBodyLocations = (
    handleChange: (e: React.ChangeEvent<HTMLInputElement>, item: IGenericRecord, name: string | undefined) => void,
    handleChangeSelect: (option: SelectedOption, others?: IGenericRecord | undefined, name?: string | undefined) => void
): IBodyTable[] => [
    {
        type: ITableFieldType.CHECKBOX,
        field: 'check',
        className: 'container--standard',
        classNameTd: 'w-3',
        editableField: true,
    },
    {
        type: ITableFieldType.TEXT,
        field: 'name',
        onChange: handleChange,
        editableField: true,
        alphanumeric: true,
        className: 'h-auto',
        classNameTd: 'w-38 md:h-10 h-8.2',
    },
    {
        type: ITableFieldType.TEXT,
        field: 'address',
        onChange: handleChange,
        editableField: true,
        className: 'h-auto',
        classNameTd: 'w-38 md:h-10 h-8.2',
    },
    {
        type: ITableFieldType.SELECT_SEARCH,
        field: 'color',
        className: 'w-full',
        containerClass: 'w-32',
        editableField: true,
        onChangeSelectSearch: handleChangeSelect,
        optionsSearch: colors.map(item => ({ ...item, name: item.value })),
    },
];

/**
 * Function that returns the entries contained in the Locations table
 * 
 * @param handleChange?: (
        e: React.ChangeEvent<HTMLInputElement> - event,
        item: IGenericRecord - item being modified,
        name: string | undefined - name input
    )  - event that is executed when doing a handlechange
 * @returns IBodyTable[]
 */
export const fieldsBodyAppointment = (
    typesAppointment: IGenericRecord,
    locations: IOptionSelect[],
    handleChange: (e: React.ChangeEvent<HTMLInputElement>, item: IGenericRecord, name: string | undefined) => void,
    handleChangeSelect: (option: SelectedOption, others?: IGenericRecord | undefined, name?: string | undefined) => void
): IBodyTable[] => {
    const { virtual, inPerson } = typesAppointment;

    return virtual && !inPerson
        ? [
              {
                  type: ITableFieldType.CHECKBOX,
                  field: 'check',
                  className: 'container--standard',
                  classNameTd: 'w-3',
                  editableField: true,
              },
              {
                  type: ITableFieldType.TEXT,
                  field: 'name',
                  onChange: handleChange,
                  editableField: true,
                  alphanumeric: true,
                  className: 'h-auto',
                  classNameTd: 'w-38 md:h-10 h-8.2',
              },
              {
                  type: ITableFieldType.SELECT_SEARCH,
                  field: 'duration',
                  className: 'w-full',
                  containerClass: 'w-32',
                  editableField: true,
                  onChangeSelectSearch: handleChangeSelect,
                  optionsSearch: duration.map(item => ({ ...item, name: item.value })),
              },
          ]
        : [
              {
                  type: ITableFieldType.CHECKBOX,
                  field: 'check',
                  className: 'container--standard',
                  classNameTd: 'w-3',
                  editableField: true,
              },
              {
                  type: ITableFieldType.TEXT,
                  field: 'name',
                  onChange: handleChange,
                  editableField: true,
                  alphanumeric: true,
                  className: 'h-auto',
                  classNameTd: 'w-38 md:h-10 h-8.2',
              },
              virtual &&
                  inPerson && {
                      type: ITableFieldType.SELECT,
                      field: 'type_appointment',
                      onChangeSelect: handleChangeSelect,
                      editableField: true,
                      alphanumeric: true,
                      className: 'h-auto',
                      options: optionTypeAppointment,
                      classNameTd: 'w-40.80 md:h-10 h-8.2',
                  },
              {
                  type: ITableFieldType.SELECT_SEARCH,
                  field: 'location',
                  className: 'w-full',
                  containerClass: 'w-32',
                  editableField: true,
                  onChangeSelectSearch: handleChangeSelect,
                  optionsSearch: locations.map(item => ({ ...item, name: item.value })),
              },
              {
                  type: ITableFieldType.SELECT_SEARCH,
                  field: 'duration',
                  className: 'w-full',
                  containerClass: 'w-32',
                  editableField: true,
                  onChangeSelectSearch: handleChangeSelect,
                  optionsSearch: duration.map(item => ({ ...item, name: item.value })),
              },
          ];
};

/**
 * Validates the data that is added
 *
 * @param devices: IGenericRecord[] - device list
 * @param onSubmit: boolean - variable that identifies if a shipment has already been made
 * @returns IGenericRecord[]
 *  */
export const validateTable = (devices: IGenericRecord[], onSubmit: boolean): IGenericRecord[] => {
    return devices.map(device => {
        return {
            ...device,
            fieldsWithError: !device.name && onSubmit ? ['name'] : [],
        };
    });
};

/**
 * Structure table Journeys locations
 *
 * @param location: string - name company
 * @param validateDifferentSchedules: boolean - diferent journeys
 * @returns IHeaderTable[]
 *  */
export const headersTableJourneys = (location: string, validateDifferentSchedules: boolean): IHeaderTable[] => {
    return !validateDifferentSchedules
        ? [
              {
                  title: location,
                  wrapperClassName: 'w-79.25',
              },
              {
                  title: 'Jornada',
                  wrapperClassName: 'w-79.25',
              },
          ]
        : [
              {
                  title: location,
                  wrapperClassName: 'w-79.25',
              },
              {
                  title: 'Jornada 1',
                  wrapperClassName: 'w-79.25',
              },
              {
                  title: 'Jornada 2',
                  wrapperClassName: 'w-79.25',
              },
          ];
};

/**
 * Function close timepicker
 *
 * @param setTimePicker: SetStateAction<boolean> - Dispatch state
 * @returns void
 */
export const closeTimePicker = (setTimePicker: Dispatch<SetStateAction<boolean>>, name: string): void => {
    const { body } = document;
    body.addEventListener('click', (e: IGenericRecord) => {
        setTimePicker(e.target.classList.contains(name));
    });
};

/**
 * list of days of the week to select on each day
 *
 * @returns IGenericRecord[]
 *  */
export const journeys = [
    {
        day: 'Domingo',
        workingDay: '',
    },
    {
        day: 'Lunes',
        workingDay: '',
    },
    {
        day: 'Martes',
        workingDay: '',
    },
    {
        day: 'Miercoles',
        workingDay: '',
    },
    {
        day: 'Jueves',
        workingDay: '',
    },
    {
        day: 'Viernes',
        workingDay: '',
    },
    {
        day: 'Sabado',
        workingDay: '',
    },
];

/* It is likely being used to
represent a value that indicates that a certain time slot or option is not available. */
export const NOT_AVAILABLE = 'No disponible';

/* A constant for location */
export const LOCATION = 'location';

/* A constant for location duration */
export const DURATION = 'duration';

/* A constant for type_appointment */
export const TYPE_APPOINTMENT = 'type_appointment';

/**
 * A validation message
 */
export const VALIDATE_SINGULAR_ERROR = '*El campo resaltado es obligatorio';

/**
 * A validation message
 */
export const VALIDATE_PLURAL_ERROR = '*Los campos resaltados son obligatorios';
