import { typeInvoice } from '@constants/ElectronicInvoice';

export const urls = {
    login: '/auth/login',
    register: '/auth/register',
    userData: '/api/auth/me',
    migrationAccout: '/api/companies-migrate',
    updateIsFirstLogin: (userId: string): string => `/api/auth/user/update-first-login/${userId}`,
    company: {
        get: (companyId: string): string => `/api/company/${companyId}`,
        company: '/api/company',
        updateCompanyAccountCreated: '/api/company/update-account-created',
        getPlanHistory: '/api/company/memberships/history',
        physicalStore: '/api/company/physical-store',
        postPhysicalStore: '/api/company/physical-store',
        deletePhysicalStore: '/api/company/physical-store/physicals-or-points',
        postCancelMembership: '/api/company/memberships/cancel-memberships',
        activeModules: `/api/company/memberships/details`,
        binnacleMembership: `/api/company/memberships/binnacle`,
        devices: '/api/companies-devices',
        deleteDevices: '/api/companies-devices/many',
        companyTaxes: '/api/company-taxes',
        updateCompanyCurrencies: (companiesForeignExchange: string): string =>
            `/api/company/companies-foreign-exchange/${companiesForeignExchange}`,
        reactivePayment: '/api/company/memberships/reactivate-recurring-payment',
        removePhysicalStore: '/api/company/physical-store/many',
        companiesAdministration: '/api/company/companies-administration',
    },
    utils: {
        withAuth: '/auth/utils',
        main: 'utils',
        unit_measurements: '/utils/unit-measurements',
        taxes: '/utils/taxes/IVA',
        membership_modules: '/utils/membership-modules',
        membership_types: '/utils/membership-types',
        fiscal_responsibility: '/utils/fiscal-responsibility',
        dynamic_request: '/utils/dynamic-request',
        consulting_area: '/utils/consulting-area',
        tax_payer: '/utils/type-tax-payer',
        customQuery: '/utils/custom-query',
        annulation: '/utils/reason-rejections/annulation',
        paymentMethods: '/utils/payment-methods/by-type',
        paymentMethodsList: '/utils/payment-methods',
        getLedgerAccounts: '/utils/ledger-accounts',
        getFormFields: '/utils/form-fields',
        getDocumentTypes: '/utils/document-types',
        getCountries: '/utils/countries',
        getDepartments: '/utils/departments',
        getCities: '/utils/cities',
        getDepartmentsForCountry: (country_id: string): string => `/utils/departments/countries/${country_id}`,
        getCitiesForDepartment: (department_id: string): string => `/utils/cities/departments/${department_id}`,
        getCiius: `/utils/ciius`,
        getReasonRejections: `/utils/reason-rejections`,
        getInflation: '/utils/global-variables/get-inflation',
    },
    password: {
        recoverPassword: '/api/users/password/email',
        changePassword: '/api/users/password/reset',
    },
    membership: {
        history: (companyId: string): string => `company/membership/${companyId}`,
        activeMemberships: (companyId: string): string => `/api/company/active-memberships/${companyId}`,
        activeStatusTransaction: '/api/company/memberships/validate-status-transaction',
        freeSupportDocuments: `/api/company/memberships/validate-access-free-documents`,
        createPurchaseProcess: `/api/purchase-process`,
    },
    politic: {
        politic: '/api/politic',
        privacyPurposes: `/api/politic/privacy-purposes`,
    },
    inventory: {
        uniqueProducts: (name: string): string => `/inventories/unique-products/${name}`,
        uploadFile: '/inventory/upload-many-files',
        maxStockControl: '/inventories/warehouses/max-stock/control',
        dailyStock: '/inventories/warehouses/daily-stock',
        warehouseControlReport: '/inventories/warehouses/warehouse-control-report',
        warehouses: '/inventories/warehouses',
        warehousesList: '/inventories/warehouses/list',
        profitability: '/inventories/unique-products/profitability-report',
        profitabilityChart: '/inventories/unique-products/profitability-chart',
        companyStock: '/inventories/unique-products/warehouses/company/stock',
        unitValueProduct: '/inventories/historical-unit-value/dates',
        provisionServices: '/inventories/city-services',
        deleteDepartmentServices: '/inventories/city-services/department',
        saveDailyMovementsInventory: '/inventories/inventory-transactions/kardex/sale-purchase',
        quantitiesProductWarehouse: '/inventories/unique-products/warehouses/stock/batch',
        getUniqueProductInventory: (id: string): string => `/inventories/unique-products/initial-inventories/${id}`,
        getProductEdit: (id: string): string => `/inventories/products/assemble/${id}`,
    },
    user: '/api/users',
    users: 'users/users',
    bucket: 'bucket',
    bucketWithAuth: 'auth/bucket',
    bucketUploadFile: '/bucket/upload-file',
    internalActivitiesModifications: '/binnacle/internalActivities/modifications',
    permission: '/api/permission',
    permissions: 'permission/format',
    uniqueProducts: '/inventories/unique-products',
    products: {
        get: (companyId: string): string => `${urls.uniqueProducts}/company/${companyId}`,
        getCrud: (action: string, companyId: string): string => `${urls.uniqueProducts}/${action}/${companyId}`,
        getBuildProduct: (unique_product_id: string): string => `${urls.products.post}assemble/${unique_product_id}`,
        post: '/inventories/products',
        uploadImage: '/inventories/products/websites/images',
        getCatalog: '/inventories/products/company/catalog',
        getInitialInventory: (id: string): string => `/inventories/products/initial-inventories/${id}`,
        updateData: '/inventories/products/websites/descriptions',
        deleteImage: (id: string): string => `/bucket/bucket-detail/${id}`,
        updateImage: '/inventories/products/websites/images/update',
        getStock: '/inventories/unique-products/warehouses/stock',
        getProductServices: '/inventories/products/assemble/list',
        deleteProductService: (id: string): string => `/inventories/unique-products/company/${id}`,
        getReport: '/inventories/products/assemble/report',
        uploadFile: '/inventories/products/assemble/file',
        postProduct: '/inventories/products/assemble',
        postMassiveProducts: '/inventories/products/assemble/file/store',
        validateSku: (sku: string): string => `/inventories/products/assemble/sku/${sku}`,
        templateWithChannelsAllTaxes:
            'https://storageccxc1.s3.us-west-2.amazonaws.com/famiefi/carga-masiva/1.1+Plantilla+Excel+con+canales+ajustes+caso+especial+Impuestos+final+2.xlsx',
        templateWithoutChannelsAllTaxes:
            'https://storageccxc1.s3.us-west-2.amazonaws.com/famiefi/carga-masiva/1.2+Plantilla+Excel+sin+canales+ajustes+caso+especial+Impuestos+final+2.0.xlsx',
        templateWithChannels_iva:
            'https://storageccxc1.s3.us-west-2.amazonaws.com/famiefi/carga-masiva/2.1+Plantilla+Excel+con+canales+ajustes+caso+solo+iva.xlsx',
        templateWithoutChannels_iva:
            'https://storageccxc1.s3.us-west-2.amazonaws.com/famiefi/carga-masiva/2.2+Plantilla+Excel+sin+canales+ajustes+caso+solo+iva+2.xlsx',
        templateWithChannels_iva_inc:
            'https://storageccxc1.s3.us-west-2.amazonaws.com/famiefi/carga-masiva/3.1+Plantilla+Excel+con+canales+ajustes+caso+solo+iva+%2BINC.xlsx',
        templateWithoutChannels_iva_inc:
            'https://storageccxc1.s3.us-west-2.amazonaws.com/famiefi/carga-masiva/3.2.+Plantilla+Excel+sin+canales+ajustes+caso+solo+iva+%2BINC.xlsx',
        templateWithChannels_iva_inc_icui:
            'https://storageccxc1.s3.us-west-2.amazonaws.com/famiefi/carga-masiva/4.1+Plantilla+Excel+con+canales+ajustes+caso+solo+iva+%2BINC%2B+ICUI.xlsx',
        templateWithoutChannels_iva_inc_icui:
            'https://storageccxc1.s3.us-west-2.amazonaws.com/famiefi/carga-masiva/4.2.+Plantilla+Excel+sin+canales+ajustes+caso+solo+iva+%2BINC%2B+ICUI.xlsx',
        templateWithChannels_iva_inc_ibua:
            'https://storageccxc1.s3.us-west-2.amazonaws.com/famiefi/carga-masiva/5.1+Plantilla+Excel+con+canales+ajustes+caso+solo+iva+%2BINC%2B+IBUA.xlsx',
        templateWithoutChannels_iva_inc_ibua:
            'https://storageccxc1.s3.us-west-2.amazonaws.com/famiefi/carga-masiva/5.2+Plantilla+Excel+sin+canales+ajustes+caso+solo+iva+%2BINC%2B+IBUA.xlsx',
        templateWithChannels_iva_icui:
            'https://storageccxc1.s3.us-west-2.amazonaws.com/famiefi/carga-masiva/6.1+Plantilla+Excel+con+canales+ajustes+caso+solo+iva+%2B+ICUI.xlsx',
        templateWithoutChannels_iva_icui:
            'https://storageccxc1.s3.us-west-2.amazonaws.com/famiefi/carga-masiva/6.2+Plantilla+Excel+sin+canales+ajustes+caso+solo+iva+%2B+ICUI.xlsx',
        templateWithChannels_iva_ibua:
            'https://storageccxc1.s3.us-west-2.amazonaws.com/famiefi/carga-masiva/7.1+Plantilla+Excel+con+canales+ajustes+caso+solo+iva+%2B+IBUA..xlsx',
        templateWithoutChannels_iva_ibua:
            'https://storageccxc1.s3.us-west-2.amazonaws.com/famiefi/carga-masiva/7.2+Plantilla+Excel+sin+canales+ajustes+caso+solo+iva+%2B+IBUA.xlsx',
        massiveUploadWithChannels:
            'https://storageccxc1.s3.us-west-2.amazonaws.com/famiefi/carga-masiva/plantilla_carga_masiva_con_canales+datos_basicos_final.xlsx',
        massiveUploadWithoutChannels:
            'https://storageccxc1.s3.us-west-2.amazonaws.com/famiefi/carga-masiva/plantilla_carga_masiva_sin_canales+datos_basicos_final.xlsx',
    },
    getFile: '/bucket/document/download',
    getProofOfPayment: '/document/proof-of-payment',
    unitValueCalculation: {
        get: (companyId: string): string => `/inventories/unique-products/by-unique-products/company/${companyId}`,
        post: (): string => `${urls.uniqueProducts}/unit-costs/value-calculation`,
        postPerishableData: (companyId: string): string =>
            `/inventories/batch-details/unit-margin-profitability/company/${companyId}`,
    },
    warehouses: {
        get: '/inventories/warehouses',
        getWarehousesProduct: '/inventories/warehouses/list-products',
        getLastCodeWarehouse: `/inventories/warehouses/last-code`,
        warehouseMiniStock: (type: string): string => `/inventories/warehouses/min-stock${type ? '/' + type : ''}`,
        createInitialInventories: '/inventories/warehouses/initial-inventories',
        getInvoicesKardex: '/inventories/unique-products/kardex-invoice',
        updateWarehouseKardex: '/inventories/inventory-transactions/update-kardex-warehouse',
        getProductBatches: '/inventories/batches/get-by-warehouse-product',
        getWarehouseInitialInventory: (product_id: string): string =>
            `/inventories/unique-products/websites/initial-inventories/${product_id}`,
        saveWarehouseInitialInventory: '/inventories/unique-products/websites/initial-inventories',
        getDetailWarehouse: (idWarehouse: string): string => `/inventories/warehouses/products/${idWarehouse}`,
        putWarehouse: (idWarehouse: string): string => `/inventories/warehouses/${idWarehouse}`,
        validateDeletion: '/inventories/unique-products/eliminable',
    },
    unitCostCalculation: {
        post: '/inventories/unique-products/calculate-unit-costs',
        getUnitCost: '/inventories/unique-products/unit-cost',
        getProductCosts: (id: string): string => `/inventories/unique-products/unit-costs/${id}`,
        getServiceCosts: (id: string): string => `/inventories/unique-products/unit-costs/service/${id}`,
        updateProductCosts: '/inventories/unique-products/unit-costs',
        updateProductPerishableCosts: '/inventories/unique-products/unit-costs/perishable',
        updateServiceCosts: '/inventories/unique-products/unit-costs/services',
        deleteCosts: '/inventories/costs',
        deleteWorkforces: '/inventories/workforces',
    },
    invoice: {
        main: 'invoice',
        withAuth: 'auth/invoice',
        timeState: '/invoices/time-state/date',
        consecutive: '/invoices/consecutives',
        consecutiveByPrefix: (prefix: string): string => `/invoices/consecutives/prefix/${prefix}`,
        createTime: '/invoices/time-start-voucher',
        createInvoice: '/invoices/bills/electronic/document',
        quotes: {
            create: '/invoices/bills/quotes/',
            getById: (quoteId: string): string => `/invoices/bills/quotes/${quoteId}`,
            report: '/invoices/bills/quotes/report',
            consecutive: '/invoices/bills/quotes/consecutives/last',
            generatePDF: (quoteId: string): string => `/invoices/bills/quotes/${quoteId}/generate-pdf`,
            generateExcel: (quoteId: string): string => `/invoices/bills/quotes/${quoteId}/generate-excel`,
            sendEmail: '/invoices/bills/quotes/send-email',
            convertToInvoice: (quoteId: string): string => `/invoices/bills/quotes/${quoteId}/generate-invoice`,
            delete: (quoteId: string): string => `/invoices/bills/quotes/${quoteId}`,
        },
        createInvoiceExcel: '/invoices/bills/electronic/many-document-billing',
        editInvoice: (id: string): string => `/invoices/bills/electronic/document/${id}`,
        updateEmailCustomer: (personId: string): string => `/invoices/persons/update/${personId}`,
        issuedDocuments: '/invoices/bills/electronic/document/issued',
        documentAction: '/invoices/bills/electronic/document/action',
        reportSalesRecords: `/invoices/bills/electronic/document/report/${typeInvoice.NO_ELECTRONICS}`,
        reportIncomeEgressWarehouse: `/invoices/bills/electronic/income-expenses-billing`,
        acceptInvoice: '/invoices/bills/electronic/accept-electronic-document-by-customer',
        reportDocumentPayment: '/invoices/money-installments/report-by-documents',
        getSpecificElectronic: (id: string): string => `/invoices/bills/document/${id}`,
        createNote: '/invoices/bills/electronic/notes',
        consecutives: (id: string): string => `/invoices/consecutives/prefix/${id}`,
        downloadInvoice: (invoice_id: string): string => `/invoices/bills/download-invoice/${invoice_id}`,
        dataInvoiceExcel: (invoice_id: string): string => `/invoices/bills/download-invoice/excel/${invoice_id}`,
        updatePayment: '/invoices/money-installments/update-money-installment',
        cancelSalesInvoice: (id: string): string => `/invoices/bills/electronic/document/annulled/${id}`,
        deletePayment: (id: string): string => `/invoices/money-installments/delete-money-installment-attachment/${id}`,
        documentsStoreInstallment: '/invoices/money-installments/documents-for-store-installment',
        storeMoneyInstallments: '/invoices/money-installments/store-money-installments',
        saleCorrections: '/invoices/bills/correction-invoices',
        getRejectedInvoices: '/invoices/bills/rejected-invoice',
        getPdf: (id: string): string => `/document/electronic-invoice/invoice-preview/${id}`,
        getDetails: (id: string): string => `/invoices/bills/download-invoice/${id}`,
        getInvoiceCorrection: (id: string): string => `/invoices/bills/electronic/document/correction/${id}`,
        getInvoiceCorrectionDisplay: (id: string): string => `/invoices/bills/electronic/document/corrections/display/${id}`,
        getInvoicesCorrection: '/invoices/bills/electronic/document/summary/correction',
        getSalesReport: '/invoices/bills/sales-force',
        getElectronicDocumentSalesReport: '/invoices/bills/accounting-reports',
        getExcel: (id: string): string => `/invoices/bills/download-invoice/excel/${id}`,
        getInformationByIdentification: (id: string): string => `/invoices/customers/${id}`,
        getElectronicInvoice: (id: string): string => `/invoices/bills/electronic/document-billing/${id}`,
        getAllNotes: (id: string): string => `/invoices/bills/electronic/document-billing/all/notes/${id}`,
        getListInvoice: '/invoices/bills/electronic/document-billing',
        errorHistories: '/invoices/bills/electronic/error-histories',
        getErrorHistoriesById: (id: string): string => `/invoices/bills/electronic/error-histories/${id}`,
        getInvoicesAvailable: (companyId: string): string => `/api/invoices-available/${companyId}`,
        validateClient: '/invoices/persons/validate-person',
        getPurchaseUpdate: '/invoices/suppliers/purchase/all',
        setPurchaseUpdate: '/invoices/suppliers/purchase/update-warehouses',
        setAgreement: '/invoices/rejected-invoices',
        support: '/invoices/rejected-invoices/support',
        getListVoucherPurchase: '/invoices/bills/electronic/voucher-purchases',
        sendEmail: '/invoices/bills/send-email',
        getDocumentList: '/invoices/bills/document/list',
        getPrefixCompany: '/invoices/consecutives/last-by-prefix',
        getFinalInventory: '/invoices/websites/initial-inventory',
        getSaleWebsite: '/invoices/bills/accounting/sales',
        getShoppingWebsite: '/invoices/bills/accounting/buy',
        getFinalInventoryDay: '/invoices/bills/accounting/daily-final-inventory',
        getFinalInventoryMonth: '/invoices/bills/accounting/final-inventory-month',
        getCalculateInvoice: '/invoices/bills/get-invoice-totals',
        getDataDashboard: '/invoices/bills/recurring-dashboard-report',
        getRebroadcast: (invoice_id: string): string => `/invoices/bills/electronic/rebroadcast/${invoice_id}`,
        getSales: '/invoices/bills/accounting-dashboard-reports',
    },
    suppliers: {
        get: '/invoices/suppliers',
        getById: (id: string): string => `/invoices/suppliers/${id}`,
        putPurchaseInvoice: (id: string): string => `/invoices/bills/suppliers/${id}`,
        reports: '/invoices/bills/suppliers/reports',
        getHistory: '/invoices/suppliers/bills',
        uploadInvoice: '/invoices/vouchers/upload-voucher',
        updateScore: '/invoices/bills/qualification',
        invoice: '/invoices/suppliers/purchase/all',
        reportInvoices: '/invoices/suppliers/purchase/report',
        reportNotes: '/invoices/bills/suppliers/purchase/reports-notes',
        getInvoice: (id: string): string => `/invoices/suppliers/bills/${id}`,
        getInvoicePurchase: (id: string): string => `/invoices/bills/suppliers/purchase/specific/${id}`,
        saveNote: '/invoices/bills/suppliers/purchase/note',
        editNote: (id: string): string => `/invoices/bills/suppliers/purchase/note/${id}`,
        updateSupport: '/invoices/bills/suppliers/purchase/support-notes',
        deleteSupport: (id: string): string => `/invoices/bills/suppliers/purchase/support-notes/${id}`,
        saveEvent: '/invoices/bills/suppliers/purchase/event',
        createMandate: '/invoices/suppliers/assemble-product',
        updateMandate: (id: string): string => `/invoices/suppliers/assemble-product/${id}`,
        getSuppliers: '/invoices/suppliers/thin',
        createFileSuppliers: '/invoices/suppliers/file/store',
        validateFileSuppliers: '/invoices/suppliers/file',
        masiveCreateSuppliers:
            'https://storageccxc1.s3.us-west-2.amazonaws.com/famiefi/carga-masiva/carga_masiva_proveedores.xlsx',
        getSupplierIsCreated: (companyId: string): string => `/invoices/suppliers/is-created/${companyId}`,
    },
    support: {
        purchasingManager: '/invoices/bills/electronic/purchasing-manager',
        storeSupportDocument: '/invoices/bills/electronic/support-document',
        getSupportDocumentById: (id: string): string => `/invoices/bills/document/${id}`,
    },
    latestModifications: 'binnacle',
    notification: {
        notification_email: '/notifications/email',
        prefix_number: '/notifications/prefix-number',
        set_up_inventory: '/notifications/set-up-inventory',
        website: '/notifications/website',
        set_up: '/notifications/set-up',
        setUpSupportingDocument: '/notifications/set-up-supporting-document',
        voucher: '/notifications/email-voucher-payment',
        all: '/notifications/company/all',
        latest: '/notifications/company/latest',
        company: '/notifications/company',
        updateNotifications: '/notifications/read-state',
        daily_notification: '/notifications/daily/company',
        daily_notification_electronic_invoice: '/notifications/company/types',
        daily_notification_support_document: '/notifications/company/types',
        daily_notification_inventory: '/notifications/inventory/daily',
        daily_notification_buying_selling_process: '/notifications/daily/buy-and-sell/company',
        buy_and_sell: '/notifications/set-up-buy-and-sell',
        electronic_invoice: '/notifications/set-up-electronic-invoice',
        upload: 'notification/upload',
        send_electronic_document: '/notifications/electronic-invoice/send-electronic-document',
        history: '/notifications/notification-history',
        main_auth: 'auth/notification',
        contact_landing: '/notifications/contact-lading',
        unread: '/notifications/unread',
        getMaintenance: '/notifications/get-maintenance',
        maintenanceHasSeenModal: '/notifications/maintenance/has-seen-modal',
        updateShowModalMaintenance: '/notifications/maintenance/update-show-modal',
    },
    website: {
        main: 'website',
        websiteAuth: 'auth/website',
        initConfig: '/websites/init-config',
        uploadInitialData: '/upload-many-files',
        blog: '/websites/blog',
        websiteSetUp: '/websites/set-up',
        websites: '/websites',
        postTemplate: 'website/upload-many-files',
        rowTypes: '/websites/row-types',
        getIcons: '/bucket/icons',
        rowCustom: '/websites/row-custom',
        discount: '/inventories/unique-products/websites/discount',
        postImage: '/websites/images/upload',
        file: 'website/upload',
        updateTabName: '/websites/update-pages',
        postSection: '/websites/pages/section',
        deleteSection: (id: string): string => `/websites/pages/section/${id}`,
        postContactUs: '/websites/contact-form',
        getContactUs: (websiteId: string): string => `/websites/form/${websiteId}`,
        putContactUs: (websiteId: string): string => `/websites/contact-form/${websiteId}`,
        postPage: '/websites/add-pages',
        deletePage: (id: string): string => `/websites/delete-pages/${id}`,
        postWhatsApp: '/websites/whatsapp-button',
        updateShowValues: '/websites/show-unit-values',
        banner: '/websites/common-property/banner',
        getAnalyticsReport: (domain: string): string => `/websites/website/google-analytics/${domain}`,
        reports: '/invoices/bills/reports-website',
    },
    domain: {
        main: 'domain',
        create: '/domains/make',
        verify: '/domains/verify',
        delete: '/domains/delete',
        createHostedZone: '/domains/create-hosted-zone',
        deleteHostedZone: '/domains/delete-hosted-zone',
        nginx: '/admin-nginx',
    },
    setArticles: 'website/upload-many-files',
    createPolitic: '/bucket/politics',
    updatePolitic: '/bucket/politics/upload',
    maximumCapacity: {
        main: '/inventories/warehouses/max-stock',
        deleteWarehouses: '/inventories/warehouses/max-stock/all',
    },
    productsCompany: (companyId: string): string => `/inventories/products/company/${companyId}`,
    productsCompanyOnly: (companyId: string): string => `/inventories/products/company/without-services/${companyId}`,

    productShippingCost: {
        post: '/inventories/shipping/unique-product/store',
        getShippingCost: (companyId: string): string => `/inventories/shipping/unique-product/${companyId}`,
        deleteCountryCities: '/inventories/shipping/city-and-country',
        deleteProduct: '/inventories/shipping/unique-product/additional-shipping',
    },
    clients: {
        postConsultClient: '/invoices/persons/get-acquirer',
        postImportClient: '/invoices/customers/transform-import-acquirer',
        getAllClients: '/invoices/customers',
        getAllClientsThin: '/invoices/customers/thin',
        updateClient: (clientId: string): string => `/invoices/customers/client/${clientId}`,
        informationClient: (clientId: string): string => `/invoices/customers/client/information/${clientId}`,
        getVoucherInfo: (invoiceId: string, type: string): string => `/invoices/vouchers/${invoiceId}/${type}`,
        createClient: '/invoices/customers/add-by-electronic-invoice',
        deleteClients: '/invoices/customers',
        validateFileCustomer: '/invoices/customers/file',
        createFileCustomer: '/invoices/customers/file/store',
        validateExistence: (companyId: string): string => `/invoices/customers/is-created/${companyId}`,
        masiveCreateClients: 'https://storageccxc1.s3.us-west-2.amazonaws.com/famiefi/carga-masiva/carga_masiva_clientes.xlsx',
    },
    clientPortal: {
        getClientById: (clientId: string): string => `/invoices/customers/portal-client/${clientId}`,
        createUpdateAddress: '/invoices/customers/addresses',
        deleteAddress: (addressId: string): string => `/invoices/customers/addresses/delete/${addressId}`,
    },
    electronic_invoice: {
        main: 'electronic-invoice',
        update: 'electronic-invoice/upload',
        config: '/electronic-invoice/configuration',
        resolutions: '/api/electronic-invoice/resolutions',
        updateTypePrefix: '/api/prefixes/set-type',
        getSynchronize: `/api/prefixes/synchronize`,
        getCertificateCompanyAction: (companyId: string): string => `/electronic-invoice/configuration/${companyId}`,
        updateFields: `api/company/update-billing`,
        mainUpdate: '/api/update-billing',
        getXml: (id: string): string => `/electronic-invoice/get-xml/${id}`,
        postXml: '/electronic-invoice/get-xml',
        updateCompanyCurrencies: (companiesForeignExchange: string): string =>
            `company/companies-foreign-exchange/${companiesForeignExchange}`,
    },
    prefix: {
        get: (companyId: string): string => `prefixes/company/${companyId}`,
        getDeleteFile: (type: string): string => `/api/company/upload-company-attachment/${type}`,
        getLogo: (type: string): string => `/api/company/upload-company-attachment/${type}/logo`,
        deleteLogo: (id: string): string => `/api/company/upload-company-attachment/${id}/logo`,
        postFile: '/api/company/upload-company-attachment',
        prefix: '/api/prefixes',
        notes: '/api/prefixes/notes',
        prefixPurchaseByCompany: `/api/prefixes/purchase/company`,
        specific: '/api/prefixes/specific',
        delete: '/api/prefixes/delete',
    },
    onboarding: {
        get: '/binnacle/instructions',
    },
    bin: {
        get: '/binnacle/recycle-bin',
        restore: (id: string): string => `/binnacle/recycle-bin/restore/${id}`,
        internalActivities: (id: string): string => `/binnacle/internalActivities/employee/${id}`,
    },
    personalizedConsulting: {
        getPqrTypes: '/utils/pqrsf-types',
        getConsultingType: '/utils/consulting-types',
        getModuleQuestions: '/utils/modules',
        postConsultingPqrContact: '/binnacle/attention-records',
        postAttentionServices: '/binnacle/attention-records/service',
        sendMailData: '/binnacle/attention-records',
    },
    payment: {
        main: 'pays',
        pseBanks: '/pays/membership/pse-banks',
        pseMethod: '/pays/membership/pse',
        cashMethod: '/pays/membership/cash',
        status: (transactionId: string): string => `/pays/membership/report/${transactionId}`,
        companySetUp: '/pays/company-set-up',
        companyPayment: '/pays/company-payments',
    },
    outputProductWarehouse: {
        getInvoices: '/invoices/bills/sale-invoice-pending-loaded-inventory',
        getInvoice: (invoiceId: string): string => `/invoices/invoice-details/out-product-warehouse-stock/${invoiceId}`,
        configuration: '/invoices/config-company-invoice',
        updateUnits: '/invoices/invoice-details/out-product-warehouse',
    },
    suppliersPurchase: {
        postSupplierPurchase: '/invoices/bills/suppliers',
    },
    inventoryProductSales: {
        getProducts: '/inventories/unique-products/sales-channel',
    },
    calendar: {
        deleteEvent: (eventId: string): string => `/binnacle/events/${eventId}`,
        events: '/binnacle/events',
        getEvents: (companyId: string): string => `/binnacle/events/${companyId}`,
        locations: '/binnacle/locations',
        appointment: '/binnacle/appointment',
        workHours: '/binnacle/work-hour',
        journeys: '/binnacle/time-slot',
        email: '/notifications/send-email-calendar',
        getDailySchedules: (date: string): string => `/binnacle/landing/appointment/${date}`,
        createAppointment: '/binnacle/landing/appointment',
    },
    homeLanding: {
        trm: 'https://www.datos.gov.co/resource/dit9-nnvp.json',
    },
    pays: {
        base: 'pays',
        banks: '/pays/membership/pse-banks',
        getCardPayU: '/pays/membership/get-card-payu',
        deleteCardToken: '/pays/membership/delete-card-token',
        updateCardToken: '/pays/membership/update-card-token',
        getStatusPayment: (transactionId: string): string => `/api/company/memberships/transactions/transaction/${transactionId}`,
        setStatusPayment: '/api/company/memberships/transactions/update-json-pse',
        // Debit or credit card pay
        payWithTokenMembership: '/api/company/memberships/pay-with-token',
        payWithoutTokenMembership: '/api/company/memberships/pay-without-token',
        payAndCreateTokenMembership: '/api/company/memberships/pay-create-token',
        // PSE
        payMembershipsPse: '/api/company/memberships/pay-pse',
        // PSE
        payUsersPse: '/api/company/memberships/pay-users-pse',
    },
    gantt: {
        deleteTask: (taskId: string): string => `/binnacle/gantts/${taskId}`,
        getTasks: (companyId: string): string => `/binnacle/gantts/${companyId}`,
        postTask: '/binnacle/gantts',
    },
    product: {
        deleteCategory: (categoryId: string): string => `/inventories/categories/${categoryId}`,
        deleteVariant: (variantId: string): string => `/inventories/variants/${variantId}`,
        deleteVariantDetail: (detailId: string): string => `/inventories/variant-details/${detailId}`,
        getCategories: (companyId: string): string => `/inventories/categories/${companyId}`,
        getCategoryVariants: (productTypeId: string): string => `/inventories/variants/${productTypeId}`,
        getDefaultCategories: '/inventories/categories/default',
        postCategory: '/inventories/categories',
        postNonPerishableProduct: '/inventories/products/assemble/no-perishables',
        postPerishable: '/inventories/products/assemble/perishables',
        postService: '/inventories/products/assemble/services',
        postVariant: '/inventories/variants',
        postVariantDetail: '/inventories/variant-details',
        updateCategory: (categoryId: string): string => `/inventories/categories/${categoryId}`,
        updateVariant: (variantId: string): string => `/inventories/variants/${variantId}`,
        updateVariantDetail: (detail: string): string => `/inventories/variant-details/${detail}`,
        getCategoryCatalog: (companyId: string): string => `/inventories/categories/${companyId}`,
        postAssembleProduct: '/inventories/products/assemble/',
        getCatalogCategories: (companyId: string): string => `/inventories/products/catalog/${companyId}`,
        getDetailProduct: (productId: string): string => `/inventories/unique-products/details/${productId}`,
    },
    supportDocument: {
        reportIssuedDocuments: '/invoices/bills/electronic/support-document/issued',
    },
    createAdjustmentNote: {
        getAdjustmentNote: '/invoices/bills/electronic/support-document/annulled',
        postAdjustmentNote: '/invoices/bills/electronic/adjustment-note',
    },
    footer: {
        politics:
            'https://storageccxc1.s3.us-west-2.amazonaws.com/famiefi/3006b3a2-332c-4244-970a-67c72d9901b8/security/politic/2024-07-24-bdab638c-be41-456e-b5c4-c30216450206-1721855113.pdf',
        terms:
            'https://storageccxc1.s3.us-west-2.amazonaws.com/famiefi/3006b3a2-332c-4244-970a-67c72d9901b8/security/politic/2024-06-12-b55ce68b-981e-4d24-ad7f-b02329c0212f-1718204352.pdf',
        sic: 'https://sedeelectronica.sic.gov.co',
    },
    modificationHistory: '/binnacle/history-modifications/modifications',
    websiteNode: {
        getWebsites: '/websites/website/all',
        deletePage: (id: string): string => `/websites/page/${id}`,
        updatePages: '/websites/page',
        createOrUpdateElement: '/websites/website/create-update-elements',
        specificElement: (id: string): string => `/websites/element/${id}`,
        getWebsiteById: (id: string): string => `/websites/website/${id}`,
        postNewWebsite: '/websites/website/new-website',
        publishWebsite: '/websites/website/publish-website',
        postWhatsApp: '/websites/whatsapp-button',
        banner: '/websites/common-property/banner',
        getVideoTutorials: '/websites/video-tutorial/all',
        deleteSocialNetworkById: (id: string): string => `/websites/social-network/${id}`,
        getSocialNetworks: '/websites/social-network/all',
        commonProperty: (property: string): string => `/websites/common-property/${property}`,
        postSocialNetworks: '/websites/social-network/create-update',
    },
    instructions: {
        main: '/api/instructions',
    },
    taxObligations: 'https://www.dian.gov.co/Paginas/Vencimientos-tributarios-marzo-2024.aspx',
    payroll: {
        main: 'payroll',
        employees: '/payroll/employees',
        employee: (employeeId: string): string => `/payroll/employees/${employeeId}`,
        areas: '/payroll/areas',
        deleteAreas: '/payroll/areas/delete',
    },
    contingency: {
        main: '/api/contingency',
        getContingency: '/api/contingency/current',
        put: (id: string): string => `/api/contingency/${id}`,
    },
};
