export enum FieldName {
    ClientId = 'client_id',
    ClientName = 'name',
    Prefix = 'prefix_name',
    Name = 'name',
    Sku = 'sku',
    DocumentType = 'document_type',
    DocumentNumber = 'document_number',
    PersonType = 'person_type',
    PaymentType = 'payment_type_name',
    PaymentTypeId = 'payment_type_id',
    PaymentMethod = 'payment_method_name',
    PaymentMethodId = 'payment_method_id',
    ForeignExchangeId = 'foreign_exchange_id',
    ForeignExchangeName = 'foreign_exchange_name',
    ForeignExchangeRate = 'foreign_exchange_rate',
    Supplier = 'supplier',
    Taxes = 'taxes',
    Warehouse = 'warehouse',
    Batch = 'batch',
    Quantity = 'quantity',
    ExpirationDate = 'date_expiration',
    DiscountPercentage = 'percentage_discount',
    OperationType = 'operation_type',
    PurchaseOrderNumber = 'number_purchase_order',
    SalesManager = 'sales_manager',
    ManagerDocumentNumber = 'document_number_sales_manager',
    ManagerDocumentType = 'document_type_purchasing_manager',
    CollectionDays = 'collection_days',
    UnitCost = 'unit_cost',
    QuoteManagerDocumentType = 'manager_document_type',
    QuoteManagerDocumentNumber = 'manager_document_number',
}

export enum Modal {
    InvoiceGenerated = 'INVOICE_GENERATED',
    InvoiceRejected = 'INVOICE_REJECTED',
    Draft = 'DRAFT',
    RemoveProduct = 'REMOVE_PRODUCT',
    InvoiceInVerification = 'INVOICE_IN_VERIFICATION',
    InvoiceError = 'INVOICE_ERROR',
    ErrorDIAN = 'ERROR_DIAN',
    ContingencySave = 'CONTINGENCY_SAVE'
}
